export const homeObjectOne = {
    id: 'practice',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Our Practice',
    headline: 'The Law Offices of Rolando L. Rios',
    description: 'The Firm is dedicated to providing clients with professional, knowledgeable and attentive legal, counseling, and legislative services. The Firm centers its practice in the areas of federal and state civil litigation, including administrative, civil rights, constitutional, election, environmental justice, immigration, municipal, non-profit, public interest, school and water law and legislative consulting and litigation.',
    buttonLabel: 'Learn More',
    imgStart: false,
    img: require('../../images/books.jpg').default,
    alt: 'Books Image',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjectTwo = {
    id: 'voting-rights',
    lightBg: true,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Voting Rights',
    headline: 'Is your Right to Vote being violated every time you vote?',
    description: 'It might be! Most people think that by casting a vote their voting right is protected; however, in reality the effectiveness of your vote depends on what election system is used in your community: wards, single member districts, at large voting, etc.  All these different systems can debase or dilute your vote. Diluting your vote is in violation of the law.',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../../images/voting.jpg').default,
    alt: 'Voting Image',
    dark: true,
    primary: false,
    darkText: false,
}

export const homeObjectThree = {
    id: 'firm',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'The Firm',
    headline: 'Professional, knowledgeable and attentive legal, counseling, and legislative services.',
    description: 'The Firm centers its practice in the areas of federal and state civil litigation, specializing in immigration, voting, election, municipal, public interest, water and tort law. ',
    buttonLabel: 'Learn More',
    imgStart: false,
    img: require('../../images/rlrpicture.jpg').default,
    alt: 'Rolando Rios Law Headshot',
    dark: true,
    primary: true,
    darkText: false,
}